name: Liquid Formula
favicon: null
layout_spectrum: 0.3880910116713494
typography_spectrum: 0.09131788671948016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.40071923937648535
  lightness: 0.8455258344765753
  saturation: 0.8361931482795626
  rhythmicContrast: 0.5876001717988402
purpose: []
